# site settings
title: My Friends Wedding Site
email: your-email@example.com
description: A site for my friends wedding.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://kittysquee.github.io/wedding-site/
twitter_username: ""
github_username:  my-github-name

# Build settings
markdown: kramdown
