# site settings
title: My Friend\'s Wedding Site
email: your-email@example.com
description: A site for my friend\'s wedding.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://my-github-name.github.io/my-repository-name/
twitter_username: ""
github_username:  my-github-name

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
